### ISSUE TITLE
question for python-caffe debug problem

### ISSUE THREAD

**Issue by chenfsjz** [Russell91/ReInspect#10]
@Russell91  I have add another lstm layer in the net , it seems OK in the forward period, but broken down in the when comes to the backward. I use the  spyder,but it cannot  shows backward period on the debug mode. I try to display the information in the code but it does little help.
Does there some useful methods or tools to debug .

**Comment by Russell91** [comment]
I usually use pdb to debug when things go wrong. If post-mortem debugging doesn't work for some reason, you could also edit python/apollocaffe/cpp/_apollocaffe.pyx and add `import pdb; pdb.set_trace()` to the backward() function to figure out what's going on. Generally, you have the same tools available whenever debugging in python. If you're getting a crash in the c++ code, you can paste the error code here. Using `grep -r "your error string"` Can usually point you to the place where the error is being thrown as well.

**Comment by chenfsjz** [comment]
I use Pdb to detect the problems of my code.
s

**Comment by chenfsjz** [comment]
I use Pdb to detect the problems of my code. here is the part result of net, the training loss propagated back from the last layer of "label_loss".The new layers  I have added  were att_input23, att_e23 and so on.  And these new layer were declared in the vision.hpp.
   The code can  print the variabes  in my new layer,like "top[i]_diff: context_top_diff "; but it doesn't work in the apollocaffe's original layer such as "LstmunitLayer". I don't know what's the reason .  
   Additional, the gradient vanished down after two iterations of lstm，does it maybe my new layer cause the problem!

label_loss
ip_concat
ip_soft_conf23
att_ip_conf23
att_dropout23
att_lstm23
att_concat23
att_input23
    context_top_diff:0.000240  
    context bottom_diff: -0.000001  
att_e_normal23
att_e23
    energy:top_diff 0.000000 
att_tanh23
    ind_diff:0.000000 
    inddata:-0.001244 
    context_data:-0.001244
ip_soft_conf22
att_ip_conf22
att_dropout22
att_lstm22
att_concat22
att_input22
    context_top_diff:nan  
    context bottom_diff: nan

**Comment by Russell91** [comment]
It is difficult for me to tell exactly. If you're getting nans it is most
likely because your new layer is producing them. I would try using only one
new layer at a time and making sure everything works well. Also you can use
gdb for debugging with python! Use gdb - -args python --config config.json
for example and set a breakpoint in your c++ code. Make sure to compile
with debugging symbols as well if you do this.

**Comment by chenfsjz** [comment]
Thanks a lot, I'll try this.
