### ISSUE TITLE
multiple images at test time

### ISSUE THREAD

**Issue by shafiei** [Russell91/ReInspect#12]
Currently, in the example provided for evaluating ReInspect, images are passed to the network one by one. Is there an example showing how to pass a batch of images (not necessarily a large batch) for evaluation at once?

**Comment by Russell91** [comment]
Right now, there is little computational advantage of batching due to the parallelism saturation in the 300 LSTMs on top. We have tested batching internally, but due to the small gains (about 20%), we don't officially support it.
