### ISSUE TITLE
How long for the training time?

### ISSUE THREAD

**Issue by kingda** [Russell91/ReInspect#13]
I have put a environment that has one cpu to run reinspect.so I train this in cpu mode.when i type "python train.py --config config.json" .It starts run.And then ,it has run 1day for “Iteration 1000 - Test Loss: 0.749104”,so i hava a quesion that how long for this?

**Comment by nicodjimenez** [comment]
Good luck training networks this big with a cpu, if it takes you 1 day for 1000 iterations then it will take you 80 days at least to train.  You need a decent GPU to run these kind of models.

**Comment by kingda** [comment]
Thanks for your words.I will think about adding a good GPU to run it.+_+
