### ISSUE TITLE
Testing ReInspect model on custom data

### ISSUE THREAD

**Issue by hemanth2090** [Russell91/ReInspect#14]
Hi,

  I am testing the ReInspect model on my own data. I notice that the number of false positives are very high. Whether the confidence of prediction of the rectangle is 0.1 or 0.9, the number of false positives is very high. 

  I feel this is happening because the LSTM is failing to produce a stop symbol. I dont understand how I can reduce the number of false positives produced from the LSTM. Could someone please guide me on how I can fix this?

**Comment by Russell91** [comment]
This isn't a true solution, but you can edit the evaluation code to force the LSTM to produce at most N outputs for each cell. 

See line 79 of https://github.com/Russell91/ReInspect/blob/master/utils/__init__.py. If you use all_rects[i][j][:1], for example, you will only get the first output.

**Comment by CharlesShang** [comment]
I found the model failed to handle the large scale variation. e.g. some images contain large people
I think you need to fine-tuning the model on your data. (region_size is an important param)
I'm doing some experiments, and the results seem quite good.
