### ISSUE TITLE
generate mean idl file for custom data

### ISSUE THREAD

**Issue by hemanth2090** [Russell91/ReInspect#15]
Hi,

 I am training the reInspect model on my own dataset. Could someone please tell me how I can generate the mean.npy idl file?

**Comment by Russell91** [comment]
You will probably be fine just using the existing mean.npy file. That being said, if you want to generate your own:

    1) load up your images
    2) initialize the sum image (don't use uint8 data format)
    3) sum all the images into the sum image
    4) divide the sum images by the number of total images
    5) call np.transpose(sum_image, [2,0,1]) to put the sum image into CHW format
    6) save the result to mean.npy

**Comment by hemanth2090** [comment]
Thank you for the reply. Do I use both training and testing data for calculating the mean?

**Comment by Russell91** [comment]
It should not effect your results, and both are okay. But using training only would be the more typical choice.
