### ISSUE TITLE
_apollocaffe.so: undefined symbol: PyFPE_counter

### ISSUE THREAD

**Issue by northeastsquare** [Russell91/ReInspect#16]
*Hello, I met this error, could you help me? or give me some hints?
     8 import sy
      9 sys.path.append('/home/silva/cxxSrc/apollocaffe/python')
---> 10 import apollocaffe # Make sure that caffe is on the python path:
     11 
     12 from utils.annolist import AnnotationLib as al

/home/silva/cxxSrc/apollocaffe/python/apollocaffe/__init__.py in <module>()
----> 1 from cpp._apollocaffe import Tensor, ApolloNet, CppConfig, make_numpy_data_param, Blob
      2 import loggers
      3 import utils
      4 from time import strftime
      5 

/home/silva/cxxSrc/apollocaffe/python/apollocaffe/cpp/__init__.py in <module>()
----> 1 import _apollocaffe

ImportError: /home/silva/cxxSrc/apollocaffe/python/apollocaffe/cpp/_apollocaffe.so: undefined symbol: PyFPE_counter

*When I ran make runtest in appollocaffe src dir, I get 
[----------] 4 tests from ImageDataLayerTest/3, where TypeParam = caffe::GPUDevice<double>
[ RUN      ] ImageDataLayerTest/3.TestResize
cant not openafter if2
*** Aborted at 1450058155 (unix time) try "date -d @1450058155" if you are using GNU date ***
PC: @     0x2ae5a0d83da0 (unknown)
*** SIGSEGV (@0x0) received by PID 14315 (TID 0x2ae596073480) from PID 0; stack trace: ***
    @     0x2ae5a0b07340 (unknown)
    @     0x2ae5a0d83da0 (unknown)
    @     0x2ae59d55e90c cv::imread()
    @     0x2ae5a0038ce0 caffe::ReadImageToCVMat()
    @     0x2ae59ff9c6a7 caffe::ImageDataLayer<>::DataLayerSetUp()
    @     0x2ae59ffa3bfb caffe::BaseDataLayer<>::LayerSetUp()
    @     0x2ae59ffa3cd9 caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @           0x4cf254 caffe::Layer<>::SetUp()
    @           0x6b6ca8 caffe::ImageDataLayerTest_TestResize_Test<>::TestBody()
    @           0x85188a testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x847179 testing::Test::Run()
    @           0x847257 testing::TestInfo::Run()
    @           0x847395 testing::TestCase::Run()
    @           0x84761d testing::internal::UnitTestImpl::RunAllTests()
    @           0x85140a testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8469e1 testing::UnitTest::Run()
    @           0x4a5122 main
    @     0x2ae5a0d36ec5 (unknown)
    @           0x4ab6ff (unknown)
    @                0x0 (unknown)
make: *** [runtest] Segmentation fault (core dumped)

**Comment by Russell91** [comment]
Please 1) install caffe and verify it works. 2) follow the directions to install apollocaffe exactly. You may find https://github.com/Russell91/apollocaffe/issues/10 to be useful as well.

**Comment by northeastsquare** [comment]
Thank you for your reply.
I also met this, I have solving it for one day with no luck.
ImportError                               Traceback (most recent call last)
<ipython-input-3-f5059a448ff7> in <module>()
     10 import sys
     11 sys.path.append('/home/ccf/src/apollocaffe/python')
---> 12 import apollocaffe # Make sure that caffe is on the python path:
     13 
     14 from utils.annolist import AnnotationLib as al

/home/ccf/src/apollocaffe/python/apollocaffe/__init__.py in <module>()
----> 1 from cpp._apollocaffe import Tensor, ApolloNet, CppConfig, make_numpy_data_param, Blob
      2 import loggers
      3 import utils
      4 from time import strftime

**Comment by northeastsquare** [comment]
Thank you ,I get a new disk and reinstall, then OK.
