### ISSUE TITLE
How does reinspect use contextual information to locate the objects in an image?

### ISSUE THREAD

**Issue by CharlesShang** [Russell91/ReInspect#18]
I've spent some time on the reading the code. On testing time, it takes 1 image as input, and call 
```
net.clear_forward()
```
to clear the memory of LstmUnit, and does FP to produce the results. Then it goes to next image.

The problem is I didn't see LstmUnit layers used any contextual info (spatial). Should the LstmUnit operate on a sequence and cache intermediate results for the next computation or just like other layers? 
Did I miss something?

**Comment by nicodjimenez** [comment]
The input to the LSTM units are not raw pixels from the image, they are googlenet features.

**Comment by CharlesShang** [comment]
@nicodjimenez Thanks. 
And I also knew that. But that won't answer the problem, I think. 
I‘m still wondering how the LstmUnit reflect the usage of contextual information.

**Comment by Russell91** [comment]
The LstmUnit only operates on contextual information insofar as its googlenet input operates on contextual information. There is no sharing of Lstm information across time, or across the 20x15 grid. The googlenet features have contextual information in the surrounding 139x139 region, despite only needing a prediction in the innermost 64x64 region.

**Comment by CharlesShang** [comment]
@Russell91 Thank you! 
I've spent the last three days looking for the sharing info in Lstm.  And that solves my doubts! 
I guess we could change the LstmUnit layers to others, and still use Hungarian loss to achieve similar results. 
Have you ever done the comparison experiments?
