### ISSUE TITLE
How to test a video?

### ISSUE THREAD

**Issue by MenglaiWang** [Russell91/ReInspect#19]
I have successfully run your test program as suggested in evaluation_reinspect.ipynb. But i wonder how to test a video frame by frame instead of saving each frame as a picture.
To be more clear,in your test ,you have saved each frame as a png, then you write its name and path into a test.idl. I wanna know how can I test a video without these steps. 
Thank you!@Russell91

**Comment by Russell91** [comment]
Hey there, thanks for your enthusiasm, but unfortunately this falls outside the scope of Deep Learning or technical problems with ReInspect. Please try asking on stackoverflow instead.
