### ISSUE TITLE
Unable to detect on bottom half of image

### ISSUE THREAD

**Issue by shaun229** [Russell91/ReInspect#20]
I am trying to detect people on my own images, and I currently have a strange issue where I can only detect people on the top half of the image. See the two images below:
![img_out22](https://cloud.githubusercontent.com/assets/8981153/12273668/126d3156-b91c-11e5-961f-2f53ecfcdac1.jpg)
![img_out26](https://cloud.githubusercontent.com/assets/8981153/12273673/15d98ccc-b91c-11e5-9522-6fb1662f2908.jpg)

They are both very similar but only the top one is detecting the person. I have more examples like this one as well. Is this an issue with how I set up my config file? The image is 320x480 and I have set the grid height to 10 by 15. Thanks in advance.

**Comment by Russell91** [comment]
Hmm, that seems like you set up the configuration correctly. The regions are programmed in line 73 of utils/__init__.py. Do you mind printing the output of all the rectangles in cell_regions and posting them here?

**Comment by shaun229** [comment]
This is my print statement in get_cell_grid:
print ox - 0.5\*region_size, oy - 0.5\*region_size, ox + 0.5\*region_size, oy + 0.5\*region_size
The output, there are 150 rectangles:
-32.0 -32.0 64.0 64.0
0.0 -32.0 96.0 64.0
32.0 -32.0 128.0 64.0
64.0 -32.0 160.0 64.0
96.0 -32.0 192.0 64.0
128.0 -32.0 224.0 64.0
160.0 -32.0 256.0 64.0
192.0 -32.0 288.0 64.0
224.0 -32.0 320.0 64.0
256.0 -32.0 352.0 64.0
288.0 -32.0 384.0 64.0
320.0 -32.0 416.0 64.0
352.0 -32.0 448.0 64.0
384.0 -32.0 480.0 64.0
416.0 -32.0 512.0 64.0
-32.0 0.0 64.0 96.0
0.0 0.0 96.0 96.0
32.0 0.0 128.0 96.0
64.0 0.0 160.0 96.0
96.0 0.0 192.0 96.0
128.0 0.0 224.0 96.0
160.0 0.0 256.0 96.0
192.0 0.0 288.0 96.0
224.0 0.0 320.0 96.0
256.0 0.0 352.0 96.0
288.0 0.0 384.0 96.0
320.0 0.0 416.0 96.0
352.0 0.0 448.0 96.0
384.0 0.0 480.0 96.0
416.0 0.0 512.0 96.0
-32.0 32.0 64.0 128.0
0.0 32.0 96.0 128.0
32.0 32.0 128.0 128.0
64.0 32.0 160.0 128.0
96.0 32.0 192.0 128.0
128.0 32.0 224.0 128.0
160.0 32.0 256.0 128.0
192.0 32.0 288.0 128.0
224.0 32.0 320.0 128.0
256.0 32.0 352.0 128.0
288.0 32.0 384.0 128.0
320.0 32.0 416.0 128.0
352.0 32.0 448.0 128.0
384.0 32.0 480.0 128.0
416.0 32.0 512.0 128.0
-32.0 64.0 64.0 160.0
0.0 64.0 96.0 160.0
32.0 64.0 128.0 160.0
64.0 64.0 160.0 160.0
96.0 64.0 192.0 160.0
128.0 64.0 224.0 160.0
160.0 64.0 256.0 160.0
192.0 64.0 288.0 160.0
224.0 64.0 320.0 160.0
256.0 64.0 352.0 160.0
288.0 64.0 384.0 160.0
320.0 64.0 416.0 160.0
352.0 64.0 448.0 160.0
384.0 64.0 480.0 160.0
416.0 64.0 512.0 160.0
-32.0 96.0 64.0 192.0
0.0 96.0 96.0 192.0
32.0 96.0 128.0 192.0
64.0 96.0 160.0 192.0
96.0 96.0 192.0 192.0
128.0 96.0 224.0 192.0
160.0 96.0 256.0 192.0
192.0 96.0 288.0 192.0
224.0 96.0 320.0 192.0
256.0 96.0 352.0 192.0
288.0 96.0 384.0 192.0
320.0 96.0 416.0 192.0
352.0 96.0 448.0 192.0
384.0 96.0 480.0 192.0
416.0 96.0 512.0 192.0
-32.0 128.0 64.0 224.0
0.0 128.0 96.0 224.0
32.0 128.0 128.0 224.0
64.0 128.0 160.0 224.0
96.0 128.0 192.0 224.0
128.0 128.0 224.0 224.0
160.0 128.0 256.0 224.0
192.0 128.0 288.0 224.0
224.0 128.0 320.0 224.0
256.0 128.0 352.0 224.0
288.0 128.0 384.0 224.0
320.0 128.0 416.0 224.0
352.0 128.0 448.0 224.0
384.0 128.0 480.0 224.0
416.0 128.0 512.0 224.0
-32.0 160.0 64.0 256.0
0.0 160.0 96.0 256.0
32.0 160.0 128.0 256.0
64.0 160.0 160.0 256.0
96.0 160.0 192.0 256.0
128.0 160.0 224.0 256.0
160.0 160.0 256.0 256.0
192.0 160.0 288.0 256.0
224.0 160.0 320.0 256.0
256.0 160.0 352.0 256.0
288.0 160.0 384.0 256.0
320.0 160.0 416.0 256.0
352.0 160.0 448.0 256.0
384.0 160.0 480.0 256.0
416.0 160.0 512.0 256.0
-32.0 192.0 64.0 288.0
0.0 192.0 96.0 288.0
32.0 192.0 128.0 288.0
64.0 192.0 160.0 288.0
96.0 192.0 192.0 288.0
128.0 192.0 224.0 288.0
160.0 192.0 256.0 288.0
192.0 192.0 288.0 288.0
224.0 192.0 320.0 288.0
256.0 192.0 352.0 288.0
288.0 192.0 384.0 288.0
320.0 192.0 416.0 288.0
352.0 192.0 448.0 288.0
384.0 192.0 480.0 288.0
416.0 192.0 512.0 288.0
-32.0 224.0 64.0 320.0
0.0 224.0 96.0 320.0
32.0 224.0 128.0 320.0
64.0 224.0 160.0 320.0
96.0 224.0 192.0 320.0
128.0 224.0 224.0 320.0
160.0 224.0 256.0 320.0
192.0 224.0 288.0 320.0
224.0 224.0 320.0 320.0
256.0 224.0 352.0 320.0
288.0 224.0 384.0 320.0
320.0 224.0 416.0 320.0
352.0 224.0 448.0 320.0
384.0 224.0 480.0 320.0
416.0 224.0 512.0 320.0
-32.0 256.0 64.0 352.0
0.0 256.0 96.0 352.0
32.0 256.0 128.0 352.0
64.0 256.0 160.0 352.0
96.0 256.0 192.0 352.0
128.0 256.0 224.0 352.0
160.0 256.0 256.0 352.0
192.0 256.0 288.0 352.0
224.0 256.0 320.0 352.0
256.0 256.0 352.0 352.0
288.0 256.0 384.0 352.0
320.0 256.0 416.0 352.0
352.0 256.0 448.0 352.0
384.0 256.0 480.0 352.0
416.0 256.0 512.0 352.0

**Comment by shaun229** [comment]
I had increased my region_size to 96, when I revert it back to 64 this is the output:
-16.0 -16.0 48.0 48.0
16.0 -16.0 80.0 48.0
48.0 -16.0 112.0 48.0
80.0 -16.0 144.0 48.0
112.0 -16.0 176.0 48.0
144.0 -16.0 208.0 48.0
176.0 -16.0 240.0 48.0
208.0 -16.0 272.0 48.0
240.0 -16.0 304.0 48.0
272.0 -16.0 336.0 48.0
304.0 -16.0 368.0 48.0
336.0 -16.0 400.0 48.0
368.0 -16.0 432.0 48.0
400.0 -16.0 464.0 48.0
432.0 -16.0 496.0 48.0
-16.0 16.0 48.0 80.0
16.0 16.0 80.0 80.0
48.0 16.0 112.0 80.0
80.0 16.0 144.0 80.0
112.0 16.0 176.0 80.0
144.0 16.0 208.0 80.0
176.0 16.0 240.0 80.0
208.0 16.0 272.0 80.0
240.0 16.0 304.0 80.0
272.0 16.0 336.0 80.0
304.0 16.0 368.0 80.0
336.0 16.0 400.0 80.0
368.0 16.0 432.0 80.0
400.0 16.0 464.0 80.0
432.0 16.0 496.0 80.0
-16.0 48.0 48.0 112.0
16.0 48.0 80.0 112.0
48.0 48.0 112.0 112.0
80.0 48.0 144.0 112.0
112.0 48.0 176.0 112.0
144.0 48.0 208.0 112.0
176.0 48.0 240.0 112.0
208.0 48.0 272.0 112.0
240.0 48.0 304.0 112.0
272.0 48.0 336.0 112.0
304.0 48.0 368.0 112.0
336.0 48.0 400.0 112.0
368.0 48.0 432.0 112.0
400.0 48.0 464.0 112.0
432.0 48.0 496.0 112.0
-16.0 80.0 48.0 144.0
16.0 80.0 80.0 144.0
48.0 80.0 112.0 144.0
80.0 80.0 144.0 144.0
112.0 80.0 176.0 144.0
144.0 80.0 208.0 144.0
176.0 80.0 240.0 144.0
208.0 80.0 272.0 144.0
240.0 80.0 304.0 144.0
272.0 80.0 336.0 144.0
304.0 80.0 368.0 144.0
336.0 80.0 400.0 144.0
368.0 80.0 432.0 144.0
400.0 80.0 464.0 144.0
432.0 80.0 496.0 144.0
-16.0 112.0 48.0 176.0
16.0 112.0 80.0 176.0
48.0 112.0 112.0 176.0
80.0 112.0 144.0 176.0
112.0 112.0 176.0 176.0
144.0 112.0 208.0 176.0
176.0 112.0 240.0 176.0
208.0 112.0 272.0 176.0
240.0 112.0 304.0 176.0
272.0 112.0 336.0 176.0
304.0 112.0 368.0 176.0
336.0 112.0 400.0 176.0
368.0 112.0 432.0 176.0
400.0 112.0 464.0 176.0
432.0 112.0 496.0 176.0
-16.0 144.0 48.0 208.0
16.0 144.0 80.0 208.0
48.0 144.0 112.0 208.0
80.0 144.0 144.0 208.0
112.0 144.0 176.0 208.0
144.0 144.0 208.0 208.0
176.0 144.0 240.0 208.0
208.0 144.0 272.0 208.0
240.0 144.0 304.0 208.0
272.0 144.0 336.0 208.0
304.0 144.0 368.0 208.0
336.0 144.0 400.0 208.0
368.0 144.0 432.0 208.0
400.0 144.0 464.0 208.0
432.0 144.0 496.0 208.0
-16.0 176.0 48.0 240.0
16.0 176.0 80.0 240.0
48.0 176.0 112.0 240.0
80.0 176.0 144.0 240.0
112.0 176.0 176.0 240.0
144.0 176.0 208.0 240.0
176.0 176.0 240.0 240.0
208.0 176.0 272.0 240.0
240.0 176.0 304.0 240.0
272.0 176.0 336.0 240.0
304.0 176.0 368.0 240.0
336.0 176.0 400.0 240.0
368.0 176.0 432.0 240.0
400.0 176.0 464.0 240.0
432.0 176.0 496.0 240.0
-16.0 208.0 48.0 272.0
16.0 208.0 80.0 272.0
48.0 208.0 112.0 272.0
80.0 208.0 144.0 272.0
112.0 208.0 176.0 272.0
144.0 208.0 208.0 272.0
176.0 208.0 240.0 272.0
208.0 208.0 272.0 272.0
240.0 208.0 304.0 272.0
272.0 208.0 336.0 272.0
304.0 208.0 368.0 272.0
336.0 208.0 400.0 272.0
368.0 208.0 432.0 272.0
400.0 208.0 464.0 272.0
432.0 208.0 496.0 272.0
-16.0 240.0 48.0 304.0
16.0 240.0 80.0 304.0
48.0 240.0 112.0 304.0
80.0 240.0 144.0 304.0
112.0 240.0 176.0 304.0
144.0 240.0 208.0 304.0
176.0 240.0 240.0 304.0
208.0 240.0 272.0 304.0
240.0 240.0 304.0 304.0
272.0 240.0 336.0 304.0
304.0 240.0 368.0 304.0
336.0 240.0 400.0 304.0
368.0 240.0 432.0 304.0
400.0 240.0 464.0 304.0
432.0 240.0 496.0 304.0
-16.0 272.0 48.0 336.0
16.0 272.0 80.0 336.0
48.0 272.0 112.0 336.0
80.0 272.0 144.0 336.0
112.0 272.0 176.0 336.0
144.0 272.0 208.0 336.0
176.0 272.0 240.0 336.0
208.0 272.0 272.0 336.0
240.0 272.0 304.0 336.0
272.0 272.0 336.0 336.0
304.0 272.0 368.0 336.0
336.0 272.0 400.0 336.0
368.0 272.0 432.0 336.0
400.0 272.0 464.0 336.0
432.0 272.0 496.0 336.0

**Comment by Russell91** [comment]
Can you verify that the problem continues to occur for region sizes of 64? I can still try to help make it work for 96, but it would be great to make sure that the 96 is not impacting things.

**Comment by shaun229** [comment]
The problem does occur for region sizes of 64, I had just changed it to 96 this morning to see if it would fix the issue, unfortunately it didn't. Give me a moment and I will add you to the private repo. Thanks.

**Comment by shaun229** [comment]
It is now a public repo, https://github.com/shaun229/modified_reinspect, I have also added you as a collaborator. Let me know if you would like the data as well.

**Comment by Russell91** [comment]
@shaun229 it also occurs to me that the two images you've shown are not the same. You aren't training on one background and testing on a different background not seen during training, are you? Also, can you try just lowering the threshold for detection at evaluation time? I do have several examples of it working on larger images.

**Comment by shaun229** [comment]
I am not sure what you mean by background. I use the same zero mean throughout training and testing, and the images are of the same location as well. For a given image in the training set, I also add their left/right and up/down reflections to the training set. Originally I didn't use up/down reflections but after I noticed that I was unable to detect people at the bottom of the image, I thought that I would add those reflections in as well. 

Here is an example evaluation output of a single image and their left/right reflection and up/down reflection. The first image is the original image. I have set the confidence threshold to 0.01.
![img_out0](https://cloud.githubusercontent.com/assets/8981153/12279871/bf045a30-b93e-11e5-86b1-de57fe62c507.jpg)
![img_out1](https://cloud.githubusercontent.com/assets/8981153/12279872/c1b7d504-b93e-11e5-806a-b74cbb1af836.jpg)
![img_out2](https://cloud.githubusercontent.com/assets/8981153/12279876/c61dfda8-b93e-11e5-9a11-cebc084484dd.jpg)

Also, here the green rectangles are all the rectangles before the stitching procedure, I've noticed that during training there were no green rectangles on the bottom half of the image.
![img_out0](https://cloud.githubusercontent.com/assets/8981153/12279982/89284e3e-b93f-11e5-94a4-21a14cb63988.jpg)
![img_out2](https://cloud.githubusercontent.com/assets/8981153/12279984/8d05fb14-b93f-11e5-8118-138838175fec.jpg)

**Comment by Russell91** [comment]
Yea, thanks for showing the rectangles. Definitely verifies that there is a problem. There is some nonsense going on in the python. Can you verify that your idl files indeed have rectangles mixed throughout the images?

**Comment by shaun229** [comment]
These are the idl file values for those three images:
"all_frames/8600154-2015-08-05-00-00-00-900.jpg":  (341,8, 430, 113); <-original image
"all_frames/8600154-2015-08-05-00-00-00-900-h.jpg":  (139,8, 50, 113);  <- left/right reflection
"all_frames/8600154-2015-08-05-00-00-00-900-v.jpg":  (341,312, 430, 207); <- up/down reflection
These values are correct, I verified them myself and with another person by manually visualizing them. 

All the training images follow the same format. The only issue I can think of in the idl file is that sometimes, x1 > x2 so when that occurs, I used to swap them, on line 100 in init.py to pass the sanity check.

**Comment by shaun229** [comment]
Ok, I will try with the re-sized images of 480x640 and let you know the results.

**Comment by shaun229** [comment]
I ran on 480x640 images, but to no avail. I am not using any weight file, and this is the output after a few hundred training iterations. 
![img_out0](https://cloud.githubusercontent.com/assets/8981153/12283148/f91c2ae4-b958-11e5-87b2-d4d346e768f4.jpg)

**Comment by Russell91** [comment]
Okay, I'm going to do a fresh `make train` and make sure something crazy is not going on. But I'm pretty sure that you've just modified something somewhere in a weird way. Can you try running the original 480x640 images with the original idl file and see what happens?

**Comment by Russell91** [comment]
Wait, did you really rewrite the evaluation script and not mention this in your claim!!! I thought these images were being output from the notebook. Ridiculous man. You've got a trivial bug in your test() function that completely explains your problems. For future reference, you're supposed to reduce your test case to the minimal possible divergence from the original code before filing a bug.
