### ISSUE TITLE
where to get the data folder?

### ISSUE THREAD

**Issue by jaknap32** [Russell91/ReInspect#22]
Hi Russel,
How to get the data folder that is getting mentioned in the ipython notebook?
couldn't figure out how set the test images folder using idl files. getting the default dat folder will help :)

Also running the `apollocaffe.set_device(1)` hangs and restarts the ipython kernel!  
Is there a documentation to use reinspect :|

thanks in advance :)

**Comment by jaknap32** [comment]
`
mkdir -p data && cd data
wget http://russellsstewart.com/s/reinspect/brainwash_mean.npy
wget http://russellsstewart.com/s/reinspect/brainwash_800000.h5
wget http://datasets.d2.mpi-inf.mpg.de/brainwash/brainwash.tar
tar xf brainwash.tarmkdir -p data && cd data
wget http://russellsstewart.com/s/reinspect/brainwash_mean.npy
wget http://russellsstewart.com/s/reinspect/brainwash_800000.h5
wget http://datasets.d2.mpi-inf.mpg.de/brainwash/brainwash.tar
tar xf brainwash.tar
`
this works! :)

**Comment by desaipratik1991** [comment]
Hi
How to get the data folder?
guide me.

Thank you

**Comment by jaknap32** [comment]
![image](https://cloud.githubusercontent.com/assets/6081987/15495334/d79eb05a-21ac-11e6-8bb0-bd2ed1595c84.png)

here before doing 'make eval', just do 'make data' first

**Comment by desaipratik1991** [comment]
Thank you

**Comment by karthee320** [comment]
The download link seems invalid, could you kindly help with that?
