### ISSUE TITLE
Improving speed on prediction

### ISSUE THREAD

**Issue by hemanth2090** [Russell91/ReInspect#23]
Hi,

  In the prediction code in the ipython notebook, I see that the line below slows down the prediction by a lot. 

```
bbox_list, conf_list = forward(net, inputs, net_config, True)
```

I understand that bbox_list and conf_list correspond to the values of each of the 5 LSTM units. Is there a way in which I can decrease the time taken for the execution of the above line?

**Comment by Russell91** [comment]
This line corresponds to running the neural network on the gpu!

**Comment by hemanth2090** [comment]
Oh okay. Thank you for clarifying. Is there any way I can improve the speed of prediction using a CPU? Currently it takes about 6 seconds to predict on an image.

**Comment by Russell91** [comment]
Unfortunately, there's not too much one can do here.
