### ISSUE TITLE
export the weight from caffemodel

### ISSUE THREAD

**Issue by Tan12345** [Russell91/ReInspect#24]
How to read the weights from caffemodel and save it to other file format?

**Comment by Russell91** [comment]
You'll have to be a little more descriptive about the context of what you're trying to do.

**Comment by Tan12345** [comment]
i'm beginner at caffe. I had trained the CNN using caffe. I try to get the weights that i trained in caffe model. I heard that the weights are stored in .caffemodel file. How to read the .caffemodel file and export the weights inside the .caffemodel file to other file format?
