### ISSUE TITLE
run "make eval" error

### ISSUE THREAD

**Issue by hjl240** [Russell91/ReInspect#25]
Hi, when I run "make eval", I got error as:
vision@R730A:~/he/reinspect$ make eval
cd utils && makecython++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp"
/bin/bash: makecython++: command not found

How can I solve this problem? Thanks.

**Comment by Russell91** [comment]
Try writing `pip install runcython`

**Comment by zxy1016** [comment]
have u realized it?

**Comment by liyuming1978** [comment]
please clone https://github.com/Russell91/runcython   and set the path.   makecython++ is implemented  by the auth.
