### ISSUE TITLE
I got raw .jpg images in hand, how could I generate the .idl ground truth files?What tools should I use?

### ISSUE THREAD

**Issue by brisker** [Russell91/ReInspect#30]
I got raw .jpg images in hand, how could I generate the .idl ground truth files like the "brainwash_train.idl"? (I mean I need to manually select the ground truth bounding box by myself and I don't know how to generate the ground truth .idl files)What tools should I use?
Besides, how to generate the mean files?  Thank you!
@Russell91

**Comment by Russell91** [comment]
Hey, you might want to check out https://github.com/Russell91/TensorBox/blob/master/make_idl.py for an example tool.

**Comment by brisker** [comment]
@Russell91   Thanks for your reply! Besides, I want to ask:
1. Is the L1Loss layer the same as the SmoothL1Loss in the initial caffe?
2. I found that the Reshape Layer is defined in python_layers.py, so if I want to use it is there  anything  different from the layers defined in the caffe_layers.py?
![image](https://cloud.githubusercontent.com/assets/13804492/18382938/c67fe574-76b5-11e6-87d0-e4d5de1cf960.png)
![image](https://cloud.githubusercontent.com/assets/13804492/18382963/dfc6284a-76b5-11e6-83f0-b4e2a56d6a24.png)
![image](https://cloud.githubusercontent.com/assets/13804492/18383053/49f0f092-76b6-11e6-9ba2-76fce5a8d79d.png)

**Comment by Johnson-yue** [comment]
@Russell91 hi, the link : https://github.com/Russell91/TensorBox/blob/master/make_idl.py is not exist,
