### ISSUE TITLE
Error when adapting to my own data

### ISSUE THREAD

**Issue by brisker** [Russell91/ReInspect#31]
I have made sure that my data are all in size 640 \* 480 , why this error when I start training?(My images are in .jpg format)
Traceback (most recent call last):
  File "train.py", line 294, in <module>
    main()
  File "train.py", line 291, in main
    train(config)
  File "train.py", line 239, in train
    forward(net, input_gen.next(), config["net"])
  File "train.py", line 35, in load_idl
    target_height=net_config["img_height"])
  File "/code/apollocaffe/reinspect/utils/**init**.py", line 98, in annotation_jitter
    assert(r.x1 < r.x2 and r.y1 < r.y2)
AssertionError
make: **\* [train] error 1

**Comment by arushk1** [comment]
What was the solution to this issue?

**Comment by brisker** [comment]
@Russell

**Comment by brisker** [comment]
@Russell91

**Comment by dbolkensteyn** [comment]
I think the problem simply comes from your .idl files: The ground-truth bounding boxes should be listed in this format:

```
"file path": (top_left_x, top_left_y, bottom_right_x, bottom_right_y), ...;
```

Top-left and bottom-right are the 2 points forming the rectangle of your bounding box.

The assertion which is failing in your case checks that: {{top_left_x < bottom_right_x and top_left_y < bottom_right_y}}.
