### ISSUE TITLE
how to train my own data from scratch without weights_file?

### ISSUE THREAD

**Issue by brisker** [Russell91/ReInspect#33]
how to set the paramters in config.json to train from scratch without pretrained model?
 "solver": { 
        "base_lr": 0.2,
        "max_iter": 200000,
        "test_iter": 500,
        "test_interval": 1000,
        "momentum": 0.5,
        "random_seed": 2,
        "clip_gradients": 0.1,
        "gamma": 0.8,
        "stepsize": 100000,
        "weights": ""
    },

**Comment by Russell91** [comment]
Just modify train.py and comment out the model load lines.
