### ISSUE TITLE
Can the number of LSTM controllers--300 be modified in the code?

### ISSUE THREAD

**Issue by brisker** [Russell91/ReInspect#34]
I looked into the code but can not find where the author defined the parameter--300(15 \* 20) described in the paper. So if I changed both the CNN architecture(maybe vggnet or zfnet) and the input image size ,and the CNN output feature map size changed from 15 \* 20  to 31 \* 31, do I need any change in the code that indicates that 300 is replaced by 31 \* 31=961?(except in the config.json file)

**Comment by Russell91** [comment]
Yea, the numbers 15 and 20 are in 2 lines within the json file. You can just modify those to 31, 32.

**Comment by brisker** [comment]
why not 31 * 31？

发自我的 iPhone

**Comment by ml9951** [comment]
@brisker, did you figure this out?
