### ISSUE TITLE
I replace the googlenet with vggnet pretrained model, the training went well but when I run test.py, the bounding boxes are just in the top left corner in the test image. Why?(vggnet output size is 31*31)

### ISSUE THREAD

**Issue by brisker** [Russell91/ReInspect#35]
I make sure that the training process went well, I added "print (abs_cx,abs_cy,w,h,conf)" in the test.py line 68 and got this(part of it):
(21, 38, 34.730034, 33.405338, 0.47580633)
(15, 39, 37.085682, 34.380287, 0.59705061)
(19, 40, 38.540291, 34.062744, 0.63981855)
(30, 39, 36.952221, 33.679222, 0.64361179)
(45, 39, 37.614788, 35.532516, 0.53727657)
(65, 36, 37.687569, 35.020634, 0.3192482)
(80, 32, 38.068748, 33.452576, 0.32980791)
(93, 30, 37.895451, 32.795353, 0.42067015)
(108, 31, 37.347561, 33.465496, 0.44270936)
(124, 37, 36.663826, 34.275047, 0.43266109)
(137, 39, 36.212067, 33.776924, 0.45708805)
(151, 38, 36.530724, 33.108349, 0.49392083)
(170, 35, 36.235176, 32.28331, 0.49919826)
(184, 34, 35.579971, 32.392361, 0.50950748)
(196, 32, 35.646965, 32.232277, 0.50838321)
(212, 29, 35.387539, 31.509975, 0.43380085)
My input image is 480 \* 480(and I fix some parameters of vggnet and the output size of vggnet is 31 \* 31), it seems that the abs_cx and abs_cy  is just always below 240, could you please tell me where to fix this bug? Thanks a lot! @Russell91

**Comment by brisker** [comment]
Does line 96 of _init_.py matters?
![image](https://cloud.githubusercontent.com/assets/13804492/18815737/99178e6c-836b-11e6-91a8-7669a46f12c2.png)
Or does /utils/rect.py line 11-16 matters?
![image](https://cloud.githubusercontent.com/assets/13804492/18815743/c1e37dce-836b-11e6-9fb8-6ee61adc4d69.png)

**Comment by lapvision** [comment]
you must change the cell_size in _init_.py (line:76)
the output size of inception_5b/output is 1024x15x20, so the cell_size = 480/15 = 32. 
If the output size of layer, which will be connected to lstm layer, is not 15x20xN, you must change the cell_size.

**Comment by jongsony** [comment]
@brisker I wonder can you share your vggnet.py?
Thanks in advance
