### ISSUE TITLE
cross_entropy loss definition

### ISSUE THREAD

**Issue by brisker** [Russell91/ReInspect#36]
![image](https://cloud.githubusercontent.com/assets/13804492/19148266/688fa9e2-8bee-11e6-849a-0c90d1c6bb6b.png)
@Russell91 
So does the definition of 
![image](https://cloud.githubusercontent.com/assets/13804492/19148281/79c53e48-8bee-11e6-8dea-a8a661a28716.png)
means that if a candidate bounding box is matched to a ground truth box, then 
![image](https://cloud.githubusercontent.com/assets/13804492/19148304/a2d91b88-8bee-11e6-84ee-3f76a841e230.png) is 1 , otherwise it is 0 ?

**Comment by Russell91** [comment]
Yea, that's correct.
