### ISSUE TITLE
Unable to download brainwash pre-trained weights and mean image

### ISSUE THREAD

**Issue by Vishwa34** [Russell91/ReInspect#49]
Getting Bad Gateway error while trying to reach http://russellsstewart.com to download required files for evaluation_reinspect. It seems like the website is down.
Few other people are facing the same issue [here](https://github.com/TensorBox/TensorBox/issues/236) while downloading files from TensorBox from last 15 days.
Is there any other source to download these files??

**Comment by ttywhu** [comment]
I also need the pre-trained weights and mean image.

**Comment by YangXiangChen** [comment]
I need the pre-trained weights and mean image too. Can anyone provide these files?

**Comment by Johnson-yue** [comment]
Yes, I also need these files , anyone can provide?

**Comment by haoli-buaa** [comment]
I uploaded the data to  :      `http://pan.baidu.com/s/1kVGEYnt`

**Comment by Vishwa34** [comment]
Thank you and I think original site is also working now

**Comment by ujsyehao** [comment]
@haoli-buaa Hi, Can you run the demo successfully? I have errors

**Comment by xuguozhi** [comment]
@haoli-buaa 不错，测试样例能跑起来了吗？

**Comment by karthee320** [comment]
Can anyone help me in getting these files, I am not able to download both in the original site as well as in Baidu's
