### ISSUE TITLE
Lock up ipython example? 

### ISSUE THREAD

**Issue by lolz0r** [Russell91/ReInspect#5]
Hello!
I have read your paper and tried out the code. I have managed to train the net on a custom data source (test loss less then 0.04!) but now I am having trouble running the ipython notebook code! 

It seems to continuously run (more then 20 minutes)

test_list = list(itertools.islice(
        load_idl_list(config["data"]["test_idl"], data_mean, config["net"], False),
        0,
        num_test_images))

I have tried it with a test idl of only 300 images and updated num_test_images to match.

Please let me know if you have any insight on this issue. 

Best wishes,
Michael

**Comment by lolz0r** [comment]
After a little debugging it looks like the ipython code for testing out the net is not too resilient to image data loading errors. :) Fixed.

**Comment by Russell91** [comment]
Great, I was confident you were going to be able to fix this one yourself :). However, if you think the notebook could be made more resilient, feel free to make a recommendation.

**Comment by darshanhegde** [comment]
@lolz0r Could you please tell me what the issue was and how you fixed it ? In my case, I'm running out of CPU memory while trying to load test_idl file.

**Comment by Russell91** [comment]
@darshanhegde can you be more specific about where in the load_idl_list function you are using up memory?

**Comment by lolz0r** [comment]
When I get to a computer (maybe Sunday) I'll share my changes.

On Oct 2, 2015 3:50 PM, Russell Stewart <notifications@github.com> wrote:
@darshanhegde can you be more specific about where in the load_idl_list function you are using up memory?

---

**Comment by lolz0r** [comment]
In words my fix was to track down where we load the images (imread) and ensure it was calling it via an import of cv2. Then verify the result of the read and if it was bad print the filename and quit. Then manually remove the offending file from the idl.

Hope this helps!

On Oct 2, 2015 3:50 PM, Russell Stewart <notifications@github.com> wrote:
@darshanhegde can you be more specific about where in the load_idl_list function you are using up memory?

---

**Comment by darshanhegde** [comment]
I had little mis-understanding about what "load_idl_list" function does ! I failed to account for the fact that it's a never ending generator. I was doing list(load_idl_list(...)) which obviously runs out of memory. Thanks for the help and sorry for the trouble.

**Comment by Russell91** [comment]
Okay, I've renamed this function to reduce confusion.
