### ISSUE TITLE
Converting .caffemodel to .hd5 format

### ISSUE THREAD

**Issue by darshanhegde** [Russell91/ReInspect#6]
In the original paper, GoogLeNet part is initialized with pre-trained GoogLeNet on the same data-set in Overfeat fashion. This helps the Conv Net features adapt to the new data-set fairly quickly. I'm trying to apply ReInspect to a different dataset and have a network trained in Overfeat fashion, but in .caffemodel format. Are there any tools to convert between the .caffemodel <--> .hd5 model formats ?

**Comment by Russell91** [comment]
Simply call net.load(caffemodel) or net.save(caffemodel). The train.py
loads the googlenet caffemodel by default, for example.

**Comment by darshanhegde** [comment]
Thanks.
