### ISSUE TITLE
evaluation_reinspect.ipynb is invalid ipython notebook

### ISSUE THREAD

**Issue by futurely** [Russell91/ReInspect#7]
The error of running `ipython notebook evaluation_reinspect.ipynb` is as follows.
```
 Unreadable Notebook: /home/user/Codes/ApolloCaffe/ReInspect/evaluation_reinspect.ipynb NotJSONError('Notebook does not appear to be JSON: u\'{\\n "cells": [\\n  {\\n   "cell_type": "...',)
```
The [online notebook viewer](http://nbviewer.ipython.org/github/Russell91/ReInspect/blob/master/evaluation_reinspect.ipynb) also can't display it.
```
400 : Bad Request

We couldn't render your notebook

Perhaps it is not valid JSON, or not the right URL.

If this should be a working notebook, please let us know.

The error was: Error reading JSON notebook
```

**Comment by Russell91** [comment]
Okay, looks like there are some good reasons for not editing .ipynb files with vim :). This should be fixed now.
