### ISSUE TITLE
tmp/reinspect.png not found

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [Russell91/ReInspect#8]
tmp/reinspect.png not found

**Comment by AKSHAYUBHAT** [comment]
Its also not required in the Ipython notebook. also you forgot
````python
 import numpy as np
````

**Comment by Russell91** [comment]
Cool, thanks for the reports!

**Comment by AKSHAYUBHAT** [comment]
Also you might want to update the default gpu to 0, otherwise it will silently change to cpu mode
````
python train.py --config config.json --gpu -0
````
