### ISSUE TITLE
Question about the size of the bounding box

### ISSUE THREAD

**Issue by wangchuan** [Russell91/ReInspect#9]
I have a question about the size of the bounding box. In the first paragraph of section **Implementation details** in your paper, you mention
> We constructed our model to encode an image into a 15x20 grid of 1024-dimensional top level GoogLeNet features. Each cell in the grid has a receptive field of size `139x139`, and is trained to produce a set of distinct bounding boxes in the center `64x64` region. The `64x64` size was chosen to be large enough to capture challenging local occlusion interactions. Larger regions may also be used, but provide little additional on our scenes, where few occlusion interactions span that scale. 300 distinct LSTM controllers are run in parallel, one for each 1x1x1024 cell of the grid.

My questions are:
1. What is the maximal size of the bounding box, `139x139` or `64x64`?
2. What if there exists ever larger bounding boxes? How does your method handle bounding boxes larger than 
	- `64x64` but smaller than `139x139`: saying a bounding box is `100x100`? or
	- `139x139`: saying a bounding box is `200x200`?

**Comment by Russell91** [comment]
Great question. There is actually no limit to the size of predicted bounding boxes - they are just inner product outputs from the convnet that are trained with regression. However, training will work poorly for boxes that are not contained within the receptive field. So what do the numbers mean?

139x139 is the receptive field size for each predictive neuron. This is the square of pixels that that neuron has access to. 64x64 is what you might call the target region. The neuron is trained to predict any people whose head falls within that target region. People who are within the receptive field but outside the target field are not supposed to be detected. They would be false positives.

If you have boxes that are significantly larger, I suggest you downscale your images in the short term and consider a multiscale approach in the long term. Another quick hack is to use a slicelayer to grab 500 of the 1024x15x20 channels, and feed them through an average pooling layer with a 5x5 kernel. Then concatenate those 500 neurons with the other 524 neurons, and feed the result into the lstm. This will give a total receptive field of 139 + 128 x 139 x 128, which could be a big boost.

**Comment by Russell91** [comment]
Closing this. Hopefully we were able to answer your questions well enough.

**Comment by brisker** [comment]
@wangchuan   @Russell91   The googlenet inception5b output size is 1024*7*7, so what does 1024*15*20 mean in the  paper?
![image](https://cloud.githubusercontent.com/assets/13804492/18465499/aa9c27c0-79c9-11e6-87c5-c8b79a678af9.png)

**Comment by gregary** [comment]
@brisker 
The googlenet inception5b output size is 1024 * 7 * 7 when the input image is 224 * 224 * 3.
In Russell's paper ,the input image's size is 480 * 640 * 3, and the output is 1024 * 15 * 20.
224/34 = 7,480/32=15,640/32=20

**Comment by Russell91** [comment]
@gregary yea that is correct

**Comment by brisker** [comment]
@Russell91 
Hello, in line 73 of _init_.py defines the cell_size:
def get_cell_grid(cell_width, cell_height, region_size):

    cell_regions = []
    cell_size = 32
but what is the meaning of cell_size?  I know that the input image size 480 * 640  / 32 equals the grid size  15*30 ,but what is the meaning of 32?
Second, in your paper you mentioned each cell can predict boxes in the central 64*64 region. So is  the number 64  a parameter that can be modified in the code or it is determined by the cell_size=32 ? If it is the latter one, what is the relationship between this two ?
Thanks a lot!
